---
# tasks file for mariadb
- name: install mariadb pkg
  yum:
    name: "{{item}}"
    state: present
  with_items: 
    - mariadb-server
    - mysql
    - MySQL-python
  notify: service mariadb restart

- name: service mariadb restart
  service:
    name: mariadb
    state: started

- name: create new database
  mysql_db:
    name: "{{ db_user_pass_dbname }}"
    state: present

- name : create database user
  mysql_user:
    name: "{{ db_user_pass_dbname }}"
    password: 'lamp'
#    encrypted: yes
    priv: '*.*:ALL'
    state: present
